### ISSUE TITLE
Maven does not compile because of 'release' flag in pom.xml

### ISSUE THREAD

**Issue by ChristophBaierATB** [thymeleaf/thymeleafexamples-gtvg#7]
Following the instructions in the README, this error occurred after executing "mvn clean" and "mvn compile":

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project gtvg: Fatal error compiling: invalid flag: --release -> [Help 1]

The problem lies within the pom.xml, and it occurred the first time in commit 6ee0a8bc1bf6ffef2d3838df72ba26e635d0d6d2. The issue could be solved by deleting the line:
<maven.compiler.release>${java.version}</maven.compiler.release>

**Comment by shiftplusc** [comment]
which version of JDK you are using to compile the project? I am using 11 and it is working fine. but I found that if I switch to JDK1.8, the error above would pop up.

**Comment by ChristophBaierATB** [comment]
Ah sry, my bad. You are right, it works using JDK 11. Thanks.
